name: Build Movie Poster Service Image using ACR

on:
  push:
    paths:
      - 'src/movie_poster_svc/**'
      - '.github/workflows/deploy_movie_poster_service.yml'
    branches:
      - main
  workflow_dispatch:


env:
  ACR_NAME: azrambiacrb76s6utvi44xo    # set this to your ACR's name
  
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  # checkout the repo 
  - uses: actions/checkout@v3
    name: Checkout to the branch

  - uses: azure/login@v1
    name: Azure Login
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}


    
  - name: Build and Deploy Container App
    uses: azure/container-apps-deploy-action@v1
    with:
      appSourcePath: ${{ github.workspace }}/src/movie_poster_svc
      acrName: ${{ env.ACR_NAME }}
      imageToBuild: ${{ env.ACR_NAME }}.azurecr.io/azure-rambi/movie_poster_svc:${{ github.sha }}
      containerAppEnvironment: azrambi-env-b76s6utvi44xo
      containerAppName: movie-poster-svc-b76s6utvi44xo
