# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy Azure Resources - azure-rambi

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/deploy_azure_resources.yml'
    branches:
      - main
  workflow_dispatch:

env:
  AZ_RESOURCE_GROUP: azrambi                  # set this to your resource group name
 
jobs:
 configure-apim:
  runs-on: ubuntu-latest
  steps:
  # checkout the repo 
  - uses: actions/checkout@v3
  # **Azure Login**
  - name: Azure Login
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
  # **Deploy Azure Resources using Bicep**
  - name: Deploy Bicep file
    uses: azure/arm-deploy@v1
    with:
      subscriptionId:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      resourceGroupName: ${{ env.AZ_RESOURCE_GROUP }}
      template: infra/DeployAzureResources.bicep
      failOnStdErr: false
      scope: resourcegroup        
  # Azure Logout
  - name: Azure Logout
    if: always()
    run: az logout
 