name: Build and deploy Movie Poster Service to Azure Container Apps - azure-movie-poster-service

on:
  push:
    paths:
      - 'src/movie_poster_svc/**'
      - 'requirements.txt'
      - '.github/workflows/deploy_movie_poster_service.yml'
    branches:
      - main
  workflow_dispatch:


env:
  ACR_NAME: azrambiacrb76s6utvi44xo    # set this to your ACR's name
  TAG:                # tag
  PYTHON_VERSION: '3.12'                
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
  # checkout the repo 
  - uses: actions/checkout@v3
  - uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
  - name: ACR build
    id: acr
    uses: azure/acr-build@v1
    with:
      service_principal: ${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}
      service_principal_password: ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }}
      tenant: ${{ secrets.AZURE_TENANT_ID }}
      registry: ${{ env.ACR_NAME }}
      repository: azure-rambi
      image: movie_poster_svc
      folder: src/movie_poster_svc
      git_access_token: ${{ secrets.GITHUB_TOKEN }}
     
